require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HacksController do

  # This should return the minimal set of attributes required to create a valid
  # Hack. As you add validations to Hack, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { 
      "name" => "MyString",
      "description" => "Describe"
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HacksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all hacks as @hacks" do
      hack = Hack.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hacks).should eq([hack])
    end
  end

  describe "GET show" do
    it "assigns the requested hack as @hack" do
      hack = Hack.create! valid_attributes
      get :show, {:id => hack.to_param}, valid_session
      assigns(:hack).should eq(hack)
    end
  end

  describe "GET new" do
    it "assigns a new hack as @hack" do
      get :new, {}, valid_session
      assigns(:hack).should be_a_new(Hack)
    end
  end

  describe "GET edit" do
    it "assigns the requested hack as @hack" do
      hack = Hack.create! valid_attributes
      get :edit, {:id => hack.to_param}, valid_session
      assigns(:hack).should eq(hack)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hack" do
        expect {
          post :create, {:hack => valid_attributes}, valid_session
        }.to change(Hack, :count).by(1)
      end

      it "assigns a newly created hack as @hack" do
        post :create, {:hack => valid_attributes}, valid_session
        assigns(:hack).should be_a(Hack)
        assigns(:hack).should be_persisted
      end

      it "redirects to the created hack" do
        post :create, {:hack => valid_attributes}, valid_session
        response.should redirect_to(Hack.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hack as @hack" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hack.any_instance.stub(:save).and_return(false)
        post :create, {:hack => { "name" => "invalid value" }}, valid_session
        assigns(:hack).should be_a_new(Hack)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hack.any_instance.stub(:save).and_return(false)
        post :create, {:hack => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hack" do
        hack = Hack.create! valid_attributes
        # Assuming there are no other hacks in the database, this
        # specifies that the Hack created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hack.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => hack.to_param, :hack => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested hack as @hack" do
        hack = Hack.create! valid_attributes
        put :update, {:id => hack.to_param, :hack => valid_attributes}, valid_session
        assigns(:hack).should eq(hack)
      end

      it "redirects to the hack" do
        hack = Hack.create! valid_attributes
        put :update, {:id => hack.to_param, :hack => valid_attributes}, valid_session
        response.should redirect_to(hack)
      end
    end

    describe "with invalid params" do
      it "assigns the hack as @hack" do
        hack = Hack.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hack.any_instance.stub(:save).and_return(false)
        put :update, {:id => hack.to_param, :hack => { "name" => "invalid value" }}, valid_session
        assigns(:hack).should eq(hack)
      end

      it "re-renders the 'edit' template" do
        hack = Hack.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hack.any_instance.stub(:save).and_return(false)
        put :update, {:id => hack.to_param, :hack => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hack" do
      hack = Hack.create! valid_attributes
      expect {
        delete :destroy, {:id => hack.to_param}, valid_session
      }.to change(Hack, :count).by(-1)
    end

    it "redirects to the hacks list" do
      hack = Hack.create! valid_attributes
      delete :destroy, {:id => hack.to_param}, valid_session
      response.should redirect_to(hacks_url)
    end
  end

end
